apiVersion: v1
kind: Namespace
metadata:
  name: iris-blue
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: sops-age
  namespace: iris-blue
spec:
  fromNamespace: external-secrets
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: iris-blue
  namespace: iris-blue
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/warroyo/iris-blue-gitops