apiVersion: v1
kind: Namespace
metadata:
  name: iris-blue-secrets-dev
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: iris-blue-secrets-dev
  namespace: iris-blue
spec:
  interval: 10m0s
  path: ./secrets/dev
  prune: true
  targetNamespace: iris-blue-secrets-dev
  sourceRef:
    kind: GitRepository
    name: iris-blue
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  namePrefix: iris-blue-
  patches:
    - patch: |-
        apiVersion: v1
        kind: Secret
        metadata:
          name: not used
          labels:
            tenant-secret: "true"
          annotations:
            cluster-store: dc1-dev
            tenant: iris-blue                  
      target:
        kind: Secret